### ISSUE TITLE
ADD: Color

### ISSUE THREAD

**Issue by shubham-kaushal** [numldesign/numl#107]
Introduce Two New Default Colors for 'Error' and 'Success' in Theme.

**Comment by tenphi** [comment]
`error` and `success` colors are theme-agnostic.
We will add them as global pre-defined colors.

**Comment by tenphi** [comment]
`v1.0.0-beta.13` is published with new colors.
Reference: https://numl.design/reference/functions/hue#predefined-colors

Also, the `light` color is added to the theme.
