### ISSUE TITLE
New Feature: Default Spacing

### ISSUE THREAD

**Issue by shubham-kaushal** [numldesign/numl#118]
Define default spacing:
```
--xxs: .25rem
--xs: .5rem
--sm: .75rem
--md: 1rem
--lg: 1.25rem
--xl: 1.5rem
--2xl: 2rem
--3xl: 3rem
```
For custom spacing, Devs are free to override the default spacing or define as many custom spacings as required on the fly.

**Comment by tenphi** [comment]
Let's stick with the discussed set:

```
--xxs: .25rem;
--xs: .5rem;
--sm: .75rem;
--md: 1rem;
--lg: 1.5rem;
--xl: 2rem;
--xxl: 3rem;
```

`1.25rem` doesn't worth it to complicate the naming.

**Comment by tenphi** [comment]
Released.
