### ISSUE TITLE
New Feature: Add all-contributors-bot

### ISSUE THREAD

**Issue by shubham-kaushal** [numldesign/numl#119]
Purpose: To automate acknowledging contributors to our open source projects.
Solution: Add all-contributors-bot 
App: https://github.com/apps/allcontributors
Repo: https://github.com/all-contributors
Doc: https://allcontributors.org/docs/en/bot/installation

**Comment by tenphi** [comment]
@all-contributors please add @shubham-kaushal

**Comment by tenphi** [comment]
@all-contributors please add @shubham-kaushal for bug, business, design, doc, ideas, research and test.

**Comment by tenphi** [comment]
@all-contributors please add @ovr for doc

**Comment by tenphi** [comment]
@all-contributors please add @katrinLuna for doc, test, bug, and ideas.

**Comment by tenphi** [comment]
@all-contributors please add @timeshift92 for test, bug, and ideas.

**Comment by tenphi** [comment]
@all-contributors please add @andrey-skl for bug and ideas.

**Comment by shubham-kaushal** [comment]
@all-contributors please add @tenphi  for code, bug, business, design, doc, ideas, research and test.

**Comment by tenphi** [comment]
@all-contributors please add @YakovlevCoded for ideas and test.
