### ISSUE TITLE
New Feature: Introduce CI/CD

### ISSUE THREAD

**Issue by shubham-kaushal** [numldesign/numl#133]
Introduce CI/CD to improve collaborations and code quality with the maintainers and contributors.

**Comment by tenphi** [comment]
Any details on this? Any ideas on what does it suppose to do?

**Comment by shubham-kaushal** [comment]
> Any details on this? Any ideas on what does it suppose to do?

You can check the managed CI/CD best option for open source i.e. Github Actions here >>> https://github.com/features/actions

It will help in automating all our workflows of build, test, and deploy right from GitHub itself including code reviews, branch management, and issue triaging work. As Github actions is a managed service and completely free for open source, we don't have to worry about updating our CI/CD workflow, only focus on our core product.
