### ISSUE TITLE
Creation of new Components for 2d Range slider

### ISSUE THREAD

**Issue by SyedUmerHasan** [numldesign/numl#160]
In order to create something like this, I will be needing extended support of Range Slider to 2 Dimension. Or it support of canvas with supports better with numl design system.

![sddssd](https://user-images.githubusercontent.com/24965764/113023083-b9067300-919e-11eb-803c-473585c859f8.PNG)

**Comment by tenphi** [comment]
Released as `<nu-slider2d/>`.
