### ISSUE TITLE
Inputs autofocus

### ISSUE THREAD

**Issue by altgifted** [numldesign/numl#267]
Hello. What about autofocus in inputs? Can't find it in docs, but this behavior is required. 
For example: I'm landed to sign in form and first step is to fill email address and I want to be focused on email input when page's loaded

**Comment by altgifted** [comment]
autofocus attribute is not working, but i see that autofocus is transferred to an input element

**Comment by tenphi** [comment]
Hello! I've just fixed autofocusing in `v1.1.3`.

Thanks for reporting!
